Enable to start/end lesson from anywhere within main directory
Type: fix

I was able to call lesson start or lesson end commands only
within main directory ('Lessons'). I wanted to be able to end a
lesson from anywhere inside the main directory. For example from
'<lesson_num>/exercises' or '<lesson_num>/programs/sudoku'.

The lesson script has become more versatile.

diff --git a/lesson b/lesson
--- a/lesson
+++ b/lesson
@@ -50,7 +50,8 @@ HELP_MSG="Try: 'lesson -h | --help' for more information"
 TIME_STAMP=".lesson_start"
 LANGUAGE=""
 
-LESSONS_DIR="Lessons"
+MAIN_DIR_NAME="Lessons"
+MAIN_DIR_ABS_PATH=""
 LESSON_DIRS=(examples exercises theory whiteboard programs todo)
 
 declare -A FLAGS=(
@@ -88,30 +89,37 @@ MIN_COMMIT_MESSAGE_LENGTH=20
 #                           Functions                                 #
 # ------------------------------------------------------------------- #
 
-# Returns 0 if $1 is a script command
-is_command()
+# Return the absolute path of $MAIN_DIR_NAME directory.
+detect_main_dir_abs_path()
 {
-    for com in "${!COMMANDS[@]}"; do
-        [[ "$com" == "$1" ]] && return 0
+    local abs_path=$(pwd)
+
+    while [[ ! "$abs_path" =~ ^\/.+\/$MAIN_DIR_NAME$ ]]; do
+        abs_path=$(dirname "$abs_path")
     done
-    return 1
+
+    echo $abs_path
 }
 
-# Returns 0 if $1 has a '.something' at the end
-has_ext() { return $( [[ "$1" =~ ^.+\..+$ ]] ); }
+# Returns 0 if $1 'file' has a '.extension' in the end.
+has_ext()
+{
+    local file=$1
 
-# Calculates the lesson number based on $1 command (start | end)
+    return $( [[ "$file" =~ ^.+\..+$ ]] )
+}
+
+# Calculates the lesson number based on $1 'command' (start | end).
 calculate_lesson_number()
 {
     local command=$1  # start | end
+    local lesson_num=$(ls $MAIN_DIR_ABS_PATH | grep -E '[0-9]+' | sort -n | tail -1)
 
     case $command in
         start)
-            lesson_num=$(ls | grep -E '[0-9]+' | sort -n | tail -1)
             lesson_num=$(( lesson_num + 1))
             echo $lesson_num  ;;
         end)
-            lesson_num=$(ls | grep -E '[0-9]+' | sort -n | tail -1)
             echo $lesson_num  ;;
     esac
 }
@@ -125,7 +133,7 @@ detect_language()
     local cpp=0
     local py=0
 
-    for file in $(find $lesson_num -type f -printf "%f\n"); do
+    for file in $(find $MAIN_DIR_ABS_PATH/$lesson_num -type f -printf "%f\n"); do
         local extension=${file##*.}
         case $extension in
             c)
@@ -152,6 +160,7 @@ detect_language()
 print_language()
 {
     local language=$1
+
     case $1 in
         c)
             echo C      ;;
@@ -172,22 +181,24 @@ create_lesson_directories()
     local lesson_num=$1
 
     for dir in "${LESSON_DIRS[@]}"; do
-        mkdir -p "$lesson_num/$dir"
+        mkdir -p "$MAIN_DIR_ABS_PATH/$lesson_num/$dir"
     done
 }
 
+# Displayed at the beggining of lesson.
 print_start_screen()
 {
     local columns=$(tput cols)
 
-    printf "%0.s-" $(seq 1 "$columns")  # upper border
-    echo -e "\n"
+    printf "%0.s-" $(seq 1 "$columns"); echo -e "\n" # upper border
+
     echoc "Welcome to Lesson #$LESSON_NUM, $(whoami)!\n"
     [[ -n $LANGUAGE ]] && echoc "Language: $(print_language $LANGUAGE)\n"
     echoc "Remember to express your ideas:\n"
     echoc " 1. Correctly\n"
     echoc " 2. Simply\n"
     echoc " 3. Efficiently\n"
+
     printf "%0.s-" $(seq 1 "$columns")  # lower border
 }
 
@@ -212,6 +223,7 @@ check_extension()
 check_emptiness()
 {
     local file=$1
+
     if [[ ! -s $file ]]; then
         STYLE_ERRORS=$(( STYLE_ERRORS + 1 ))
         echo "Style Error: '$file' is empty." >&2
@@ -247,20 +259,24 @@ collect_file_stats()
     done
 }
 
+# Set global variables HOURS_, MINUTES_, SECONDS_ to time that has passed
+# since creation if TIME_STAMP file.
 collect_time_stats()
 {
     local lesson_num=$1
+    local time_stamp=$MAIN_DIR_ABS_PATH/$lesson_num/$TIME_STAMP
+    local duration=""
 
-    if [[ -f $lesson_num/$TIME_STAMP ]]; then
-        local duration=$(( $(date +%s) - $(stat -c "%Y" "$lesson_num/$TIME_STAMP") ))
+    if [[ -f $time_stamp ]]; then
+        duration=$(( $(date +%s) - $(stat -c "%Y" "$time_stamp") ))
         HOURS_=$(( duration / 3600 ))
         MINUTES_=$(( duration / 60 - HOURS_ * 60))
         SECONDS_=$(( duration % 60 ))
-        rm "$lesson_num/$TIME_STAMP"  # Delete a time-stamp file
+        rm "$time_stamp"  # Delete a time-stamp file
     fi
 }
 
-# Tackle wrong login/password issues
+# Tackle wrong login/password issues.
 git_push()
 {
     while true; do
@@ -269,7 +285,7 @@ git_push()
     done
 }
 
-# Tackle 'bad' commit messages
+# Tackle 'bad' commit messages.
 git_commit()
 {
     while true; do
@@ -289,19 +305,21 @@ git_commit()
     echo ""
 }
 
+# Displayed at the end of lesson.
 print_end_screen()
 {
     local columns=$(tput cols)
 
-    printf "%0.s-" $(seq 1 "$columns")
-    echo -e "\n"
+    printf "%0.s-" $(seq 1 "$columns"); echo -e "\n"  # upper border
+
     echoc "End of lesson #$LESSON_NUM. Goodbye, $(whoami)!\n"
     [[ -n $LANGUAGE ]] && echoc "Language: $(print_language $LANGUAGE)\n"
     echoc "Stats:\n"
     echoc " 1. Lesson took $HOURS_:$MINUTES_:$SECONDS_\n"
     echoc " 2. Exercises completed: $EXERCISES_COMPLETED\n"
     echoc " 3. Programs written: $PROGRAMS_WRITTEN\n"
-    printf "%0.s-" $(seq 1 "$columns")
+
+    printf "%0.s-" $(seq 1 "$columns")  # lower border
 }
 
 # ------------------------------------------------------------------- #
@@ -339,7 +357,7 @@ done
 #                           Validation                                #
 # ------------------------------------------------------------------- #
 
-# Check the <command> is given
+# Check the <command> is given.
 if [[ $# -eq 0 ]]; then
     echo "Error: missing <command> argument" >&2
     echo "$HELP_MSG" >&2
@@ -389,15 +407,14 @@ esac
 # ------------------------------------------------------------------- #
 #                           Validation                                #
 # ------------------------------------------------------------------- #
-# TODO
-# Check if inside of LESSONS_DIR directory
-if [[ ! "$(pwd)" =~ .+/$LESSONS_DIR$ ]]; then
-    if [[ ${FLAGS[force]} -ne 1 ]]; then
-        echo "Warning: Not inside '$LESSONS_DIR' directory"
-        echo "It may affect how I work"
-        read -rep "Proceed? [y/n]: " ans
-        [[ ! "$ans" =~ ^[yY]$ ]] && exit 0
-    fi
+
+# Check if inside of MAIN_DIR_NAME directory
+if [[ ! "$(pwd)" =~ ^\/.+\/$MAIN_DIR_NAME\/?.*$ ]]; then
+    echo "Error: Not inside '$MAIN_DIR_NAME' directory." >&2
+    echo $HELP_MSG >&2
+    exit 1
+else
+    MAIN_DIR_ABS_PATH=$(detect_main_dir_abs_path)
 fi
 
 # ------------------------------------------------------------------- #
@@ -483,7 +500,7 @@ if [[ ${FLAGS[start]} -eq 1 ]]; then
     # ----------------------------------------------------------- #
 
     # Check if there is a Lesson with number <lesson_num>
-    if [[ -d $LESSON_NUM ]]; then
+    if [[ -d $MAIN_DIR_ABS_PATH/$LESSON_NUM ]]; then
         echo "Error: Lesson number '$LESSON_NUM' already exists" >&2
         echo "Fix: Try another number" >&2
         exit 1
@@ -491,7 +508,7 @@ if [[ ${FLAGS[start]} -eq 1 ]]; then
 
     create_lesson_directories "$LESSON_NUM"
 
-    touch "$LESSON_NUM/$TIME_STAMP"  # Create a time-stamp file
+    touch "$MAIN_DIR_ABS_PATH/$LESSON_NUM/$TIME_STAMP"  # Create a time-stamp file
 
     print_start_screen
 
@@ -506,7 +523,7 @@ elif [[ ${FLAGS[end]} -eq 1 ]]; then
     # ----------------------------------------------------------- #
 
     # Check if there is no lesson with number <lesson_num>
-    if [[ ! -d $LESSON_NUM ]]; then
+    if [[ ! -d $MAIN_DIR_ABS_PATH/$LESSON_NUM ]]; then
         echo "Error: Lesson number '$LESSON_NUM' doesn't exist" >&2
         exit 1
     fi
@@ -514,12 +531,12 @@ elif [[ ${FLAGS[end]} -eq 1 ]]; then
     ## ANALYZE EACH DIRECTORY
 
     for dir in "${LESSON_DIRS[@]}"; do  # for each directory
-        full_dir="$LESSON_NUM/$dir"
+        full_dir="$MAIN_DIR_ABS_PATH/$LESSON_NUM/$dir"
 
         if [[ -d $full_dir ]]; then  # if directory exists
 
             for file in $(ls "$full_dir"); do  # for each file in directory
-                full_file="$LESSON_NUM/$dir/$file"
+                full_file="$MAIN_DIR_ABS_PATH/$LESSON_NUM/$dir/$file"
 
                 check_extension "$full_file"
                 check_emptiness "$full_file"
@@ -539,7 +556,7 @@ elif [[ ${FLAGS[end]} -eq 1 ]]; then
     collect_time_stats "$LESSON_NUM"
 
     # If git repo and changes were made
-    if [[ -d ".git" && -n $(git status --porcelain) ]]; then
+    if git status > /dev/null 2>&1 && [[ -n $(git status --porcelain) ]]; then
         git status; echo ""
         git add .
         git_commit
@@ -548,10 +565,10 @@ elif [[ ${FLAGS[end]} -eq 1 ]]; then
 
     print_end_screen
 
-    if isempty "$LESSON_NUM"; then
-        rmdir "$LESSON_NUM"
+    if isempty "$MAIN_DIR_ABS_PATH/$LESSON_NUM"; then
+        rmdir "$MAIN_DIR_ABS_PATH/$LESSON_NUM"
     else
-        tree "$LESSON_NUM"
+        tree "$MAIN_DIR_ABS_PATH/$LESSON_NUM"
     fi
 
 fi
